name: Example workflow for Testcafe action
on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Use Node.js 12.x
        uses: actions/setup-node@master
        with:
          version: 12.x
      - name: Run testcafe tests
        uses: ./
        with:
          args: "chrome:headless tests"
